#======================================================================
# Project settings
#======================================================================
branches:
  only:
    - develop

language: cpp
#======================================================================
# Environment
#======================================================================

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - gfortran-7
      - g++-7

#======================================================================
# Build Matrix
#======================================================================
matrix:
   include:
     - os: linux
       compiler: gcc
       sudo: false
       dist: trusty

#======================================================================
# Docker does not work on Mac
#======================================================================
services:
  - docker

before_install:
  - REPO_SOURCE_DIR=${TRAVIS_BUILD_DIR}
#======================================================================
# Clone all repos
#======================================================================
  - git clone https://github.com/jcsda/ufo-bundle.git ufo-bundle
  - git clone https://github.com/jcsda/oops.git ufo-bundle/oops
  - git clone https://github.com/jcsda/GSW-Fortran.git ufo-bundle/gsw
  - git clone https://github.com/jcsda/crtm.git ufo-bundle/crtm
  - git clone https://github.com/jcsda/ioda.git ufo-bundle/ioda
  - git clone https://github.com/jcsda/ufo.git ufo-bundle/ufo
  - git clone https://github.com/jcsda/fckit.git ufo-bundle/fckit
  - ls ${REPO_SOURCE_DIR}
  - ls ${REPO_SOURCE_DIR}/ufo-bundle
  - find . -name \* -exec chmod 777 {} \; -print

#======================================================================
# get docker image
# FROM  jcsda/docker:latest
#======================================================================
  - docker build -t jcsda/docker --build-arg=Dockerfile .  #Dockerfile handles ssh for mpi
  - docker images
  - docker run -d -t --name jcsda_container -v ${REPO_SOURCE_DIR}/ufo-bundle:/jcsda/src_repo jcsda/docker
  - docker ps -a

#======================================================================
# Here are the run steps
#======================================================================
script:
  - docker exec jcsda_container ls
  - docker exec jcsda_container ls /jcsda/src_repo
  - docker exec jcsda_container bash -c 'cp -r /jcsda/.openmpi/ ~/'
##  use cmake with flags to generate test coverage reports
  - docker exec jcsda_container bash -c 'cd /build_container && cmake -DCMAKE_MODULE_PATH=/usr/local/share/ecbuild/cmake/ -DCMAKE_BUILD_TYPE=Debug -DENABLE_GPROF=ON  /jcsda/src_repo' 
  - docker exec jcsda_container bash -c 'cd /build_container/ufo && make -j4'
  - docker exec jcsda_container bash -c 'cd /build_container/ufo && ctest'
##  run lcov inside container
  - docker exec jcsda_container bash -c 'cd /build_container/ufo && lcov --capture --directory . --output-file coverage.info'
  - docker exec jcsda_container bash -c 'cd /build_container/ufo && lcov --remove coverage.info "/usr/*" --output-file coverage.info'  #  filter system-files 
  - docker exec jcsda_container bash -c 'cd /build_container/ufo && lcov --list coverage.info'  #  debug info
##  copy coverage report to shared volume btw container and Travis
  - docker exec jcsda_container cp /build_container/ufo/coverage.info  /jcsda/src_repo/
#======================================================================
# CodeCov report
#======================================================================
after_success:
  - cd ${REPO_SOURCE_DIR}/ufo-bundle
  - bash <(curl -s https://codecov.io/bash) -t 80e931a0-8cb3-49f6-be20-462b338c57be  -X gcov -f coverage.info  #  Token is not needed for publuc repo

